{
 "title": "GPU Monitoring",
 "time": { "from": "2024-08-07T05:20:57.710Z", "to": "2024-08-07T05:23:27.562Z" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(service_name)" } },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "---\n# GPU Monitoring\n\nThis dashboard displays the usage stats of NVIDIA GPUs like temperature, utilization, memory usage and more generated using [OpenLIT](https://github.com/openlit/openlit).\n\n---"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gpu_fan_speed{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_utilization{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"})",
     "legendFormat": "Average GPU Utilization"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_temperature{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"})",
     "legendFormat": "Average GPU Temperature"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_power_draw{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"})",
     "legendFormat": "Average GPU Power Draw"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This panel displays the LLM Request Rate ",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_memory_used{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}/gpu_memory_available{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"})",
     "legendFormat": "Average GPU Memory Usage"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "{{gpu_uuid}}-{{gpu_name}}"
    },
    {
     "expr": "gpu_dec_utilization{telemetry_sdk_name=\"openlit\"}",
     "legendFormat": "{{gpu_uuid}}-{{gpu_name}}"
    },
    {
     "expr": "gpu_enc_utilization{telemetry_sdk_name=\"openlit\"}",
     "legendFormat": "{{gpu_uuid}}-{{gpu_name}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "{{gpu_uuid}}-{{gpu_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "gpu_memory_used{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "gpu_memory_free{telemetry_sdk_name=\"openlit\"}",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "gpu_memory_total{telemetry_sdk_name=\"openlit\"}",
     "legendFormat": "Memory Total"
    }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu_fan_speed{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "{{gpu_uuid}}-{{gpu_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_draw{telemetry_sdk_name=\"openlit\", service_name=~\"$application\", deployment_environment=~\"$environment\"}",
     "legendFormat": "Power Draw"
    },
    {
     "expr": "gpu_power_limit{telemetry_sdk_name=\"openlit\"}",
     "legendFormat": "Power Limit"
    }
   ]
  }
 ]
}