{
 "title": "Agent Observability",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_datasource", "label": "Metrics data source", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs data source", "query": "loki" },
   {
    "name": "deployment_environment",
    "label": "deployment_environment",
    "query": {
     "query": "label_values($deployment_environment)"
    }
   },
   {
    "name": "gen_ai_agent_name",
    "label": "Agent Name",
    "query": {
     "query": "label_values(gen_ai_agent_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img\n src=\"https://grafana.com/media/docs/grafana-cloud/ai-observability/aio11y-logo.svg\"\n width=\"100%\"\n height=\"100%\">"
   }
  },
  {
   "title": "Total Agent Invocations",
   "type": "stat",
   "description": "The total agent invocations in the selected time range.",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(gen_ai_agent_invocations_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Invocations by Source",
   "type": "stat",
   "description": "The total number of agent invocations in the selected time range, grouped by source.",
   "gridPos": { "h": 5, "w": 14, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(gen_ai_agent_invocations_total{gen_ai_agent_source=~\"$gen_ai_agent_name\"}[$__range]))) by (gen_ai_agent_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Agent Cost (USD)",
   "type": "stat",
   "description": "The total usage cost per agent in the selected time range.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gen_ai_usage_cost_USD_sum{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__range])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Per Agent (USD)",
   "type": "bargauge",
   "description": "The usage cost per agent in the selected time range.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gen_ai_usage_cost_USD_sum{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__range])) by (gen_ai_agent_name) / 1000",
     "legendFormat": "{{gen_ai_agent_name}}"
    }
   ]
  },
  {
   "title": "Percent Invocations by Source",
   "type": "bargauge",
   "description": "The total number of agent invocations in the selected time range, grouped by source.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100 ", "type": "math" }
   ]
  },
  {
   "title": "Agent Operation Duration (p95)",
   "type": "timeseries",
   "description": "95th percentile latency for AI agent operations, by agent name. 95% of operations complete within this duration. High values indicate slowdowns in specific agents.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gen_ai_agent_operation_duration_seconds_bucket{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__rate_interval])) by (le, gen_ai_agent_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Operation Duration Heatmap",
   "type": "heatmap",
   "description": "95th percentile latency for agent operations, by agent name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gen_ai_agent_operation_duration_seconds_bucket{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__rate_interval])) by (le, gen_ai_agent_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Operation Duration by Agent & Provider",
   "type": "timeseries",
   "description": "The average time spent executing an operation in the selected time range, grouped by agent name and provider.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(gen_ai_agent_name, gen_ai_provider_name) (increase(gen_ai_agent_operation_duration_seconds_sum{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__range]))\n/\nsum by(gen_ai_agent_name, gen_ai_provider_name) (increase(gen_ai_agent_operation_duration_seconds_count{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__range]))",
     "legendFormat": "{{gen_ai_agent_name}} / {{gen_ai_provider_name}}"
    }
   ]
  },
  {
   "title": "Agent Operation Rate",
   "type": "timeseries",
   "description": "The rate of completed agent operations, broken down by agent name and provider. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(gen_ai_agent_name, gen_ai_provider_name) (rate(gen_ai_agent_operation_duration_seconds_count{gen_ai_agent_name=~\"$gen_ai_agent_name\"}[$__rate_interval]))",
     "legendFormat": "{{gen_ai_agent_name}} / {{gen_ai_provider_name}}"
    }
   ]
  },
  {
   "title": "Agent Logs",
   "type": "logs",
   "description": "The logs for agent interactions. ",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"chatservice\"} |= \"_agent\"  | json | line_format \"\\n\\tName: {{.name}}\\n\\tTraceID: {{.otelTraceID}}\\n\\tSpanID: {{.otelSpanID}}\\n\\tMessage: {{.message}}\" |~ \"$gen_ai_agent_name\""
    }
   ]
  }
 ]
}