{
 "title": "TensorFlow Serving overview",
 "description": "Overview of a TensorFlow Serving instance.",
 "tags": [ "tensorflow-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(:tensorflow:serving:request_count{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(:tensorflow:serving:request_count{job=~\"$job\"}, instance)"
   },
   {
    "name": "model_name",
    "label": "Model name",
    "query": "label_values(:tensorflow:serving:request_count{job=~\"$job\",instance=~\"$instance\"}, model_name)"
   },
   { "name": "loki_datasource", "label": "Loki datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Model request rate",
   "type": "timeseries",
   "description": "Rate of requests over time for the selected model. Grouped by statuses.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(:tensorflow:serving:request_count{job=~\"$job\",instance=~\"$instance\",model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "model_name=\"{{model_name}}\",status=\"{{status}}\""
    }
   ]
  },
  {
   "title": "Model predict request latency",
   "type": "timeseries",
   "description": "Average request latency of predict requests for the selected model.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:serving:request_latency_sum{job=~\"$job\",instance=~\"$instance\",model_name=~\"$model_name\"}[$__rate_interval])/increase(:tensorflow:serving:request_latency_count{job=~\"$job\",instance=~\"$instance\",model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "model_name=\"{{model_name}}\""
    }
   ]
  },
  {
   "title": "Model predict runtime latency",
   "type": "timeseries",
   "description": "Average runtime latency to fulfill a predict request for the selected model.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:serving:runtime_latency_sum{job=~\"$job\",instance=~\"$instance\",model_name=~\"$model_name\"}[$__rate_interval])/increase(:tensorflow:serving:runtime_latency_count{job=~\"$job\",instance=~\"$instance\",model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "model_name=\"{{model_name}}\""
    }
   ]
  },
  {
   "title": "Serving overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graph build calls",
   "type": "timeseries",
   "description": "Number of times TensorFlow Serving has created a new client graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "calls" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:core:graph_build_calls{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Graph runs",
   "type": "timeseries",
   "description": "Number of graph executions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:core:graph_runs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Graph build time",
   "type": "timeseries",
   "description": "Amount of time Tensorflow has spent creating new client graphs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:core:graph_build_time_usecs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])/increase(:tensorflow:core:graph_build_calls{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Graph run time",
   "type": "timeseries",
   "description": "Amount of time spent executing graphs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:core:graph_run_time_usecs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])/increase(:tensorflow:core:graph_runs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Batch queuing latency",
   "type": "timeseries",
   "description": "Current latency in the batching queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(:tensorflow:serving:batching_session:queuing_latency_sum{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])/increase(:tensorflow:serving:batching_session:queuing_latency_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Batch queue throughput",
   "type": "timeseries",
   "description": "Rate of batch queue throughput over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "batches/s" } },
   "targets": [
    {
     "expr": "rate(:tensorflow:serving:batching_session:queuing_latency_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Container logs",
   "type": "logs",
   "description": "Logs from the TensorFlow Serving Docker container.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{name=\"tensorflow\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  }
 ]
}