name: Publish branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install utilities jq
        run: sudo apt-get install jq

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Sign plugin
        run: npx --yes @grafana/sign-plugin@latest
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}

      - name: Get plugin metadata
        id: metadata
        run: |
          sudo apt-get install jq
          
          export GRAFANA_PLUGIN_ID=$(cat dist/plugin.json | jq -r .id)
          export GRAFANA_PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)
          export GRAFANA_PLUGIN_TYPE=$(cat dist/plugin.json | jq -r .type)
          export GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.zip
          export GRAFANA_PLUGIN_ARTIFACT_SHA1SUM=${GRAFANA_PLUGIN_ARTIFACT}.sha1
          export GRAFANA_PLUGIN_ARTIFACT_ANY=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.any.zip
          export GRAFANA_PLUGIN_ARTIFACT_ANY_SHA1SUM=${GRAFANA_PLUGIN_ARTIFACT_ANY}.sha1
          
          echo "plugin-id=${GRAFANA_PLUGIN_ID}" >> $GITHUB_OUTPUT
          echo "plugin-version=${GRAFANA_PLUGIN_VERSION}" >> $GITHUB_OUTPUT
          echo "archive=${GRAFANA_PLUGIN_ARTIFACT}" >> $GITHUB_OUTPUT
          echo "archive-sha1sum=${GRAFANA_PLUGIN_ARTIFACT_SHA1SUM}" >> $GITHUB_OUTPUT
          echo "archive-any=${GRAFANA_PLUGIN_ARTIFACT_ANY}" >> $GITHUB_OUTPUT
          echo "archive-any-sha1sum=${GRAFANA_PLUGIN_ARTIFACT_ANY_SHA1SUM}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Package plugin
        id: package-plugin
        run: |
          mv dist ${{ steps.metadata.outputs.plugin-id }}
          zip ${{ steps.metadata.outputs.archive }} ${{ steps.metadata.outputs.plugin-id }} -r
          zip ${{ steps.metadata.outputs.archive-any }} ${{ steps.metadata.outputs.plugin-id }} -r
          sha1sum ${{ steps.metadata.outputs.archive }} | cut -f1 -d' ' > ${{ steps.metadata.outputs.archive-sha1sum }}
          sha1sum ${{ steps.metadata.outputs.archive-any }} | cut -f1 -d' ' > ${{ steps.metadata.outputs.archive-any-sha1sum }}
          mkdir artifacts
          mv ${{ steps.metadata.outputs.archive }} ${{ steps.metadata.outputs.archive-any }} ${{ steps.metadata.outputs.archive-sha1sum }} ${{ steps.metadata.outputs.archive-any-sha1sum }} artifacts
        shell: bash

      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            GCP_UPLOAD_ARTIFACTS_KEY=grafana/integration-artifacts-uploader-service-account:'credentials.json'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}

      - id: 'upload-artifacts'
        name: 'Upload artifacts'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: artifacts
          destination: 'integration-artifacts/${{ steps.metadata.outputs.plugin-id }}/${{ steps.metadata.outputs.plugin-version }}/main/${{ github.event.pull_request.head.sha || github.sha }}'
          parent: false
